#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl11, Flag,           sensorDigitalIn)
#pragma config(Sensor, dgtl12, Red,            sensorDigitalIn)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, PIDControl, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port6,           servoLock,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           fliperMotor,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           liftMotor,     tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

// for moving forward or backwords
static const float ticksPerInch = 0.967 * (627.2 / (4.0 * PI));

// for turning the Robot
static const float ticksPerDeg = 1.0 * (ticksPerInch * 15.5 * PI) / 360.0;

// for raising the lift
static const float ticksPerInchRaised = 3968.0/14.0; // * (627.2 * 0.75 * PI);

// used for LCD screen
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
int count = 0;

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

// used to drive the robot forward
void move(float dist, int speed, bool hold)		//used to drive the robot forward
{
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);

	setMotorTarget(rightMotor, dist*ticksPerInch, speed, hold);
	setMotorTarget(leftMotor, dist*ticksPerInch, speed, hold);

	while (!getMotorTargetCompleted(rightMotor) && !getMotorTargetCompleted(leftMotor))
		wait1Msec(10);
}

// used to turn the robot
void spin(float deg, int speed, bool hold)	//used to turn the robot
{
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);

	setMotorTarget(rightMotor, -deg * ticksPerDeg, speed, hold);
	setMotorTarget(leftMotor, deg * ticksPerDeg, speed, hold);

	// due to the way the motor targets are set, a positive degree value will turn the robot clockwise, or right
	// further, a negative value turns the robot counterclockwise, or left

	while (!getMotorTargetCompleted(rightMotor) && !getMotorTargetCompleted(leftMotor))
		wait1Msec(10);
}

// used to raise the lift
void raise (float inches, int speed, bool hold)
{
	resetMotorEncoder(liftMotor);

	setMotorTarget(liftMotor, (long)(inches * ticksPerInchRaised), speed, hold);
}
void raiseWait (void)
{
	while (!getMotorTargetCompleted(liftMotor))
		wait1Msec(10);
}

// Wait for Press
void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}

// Wait for Release
void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...

	// Declare count variable to keep track of our choice
	int count = 0;

	// Clear LCD
	clearLCDLine(0);
	clearLCDLine(1);
	// Loop while center button is not pressed
	while(nLCDButtons != centerButton)
	{
		// Switch case that allows the user to choose from 4 different options
		switch(count){
		case 0:
			// Display first choice
			displayLCDCenteredString(0, "Red Flag");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			// Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 3;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 1:
			// Display second choice
			displayLCDCenteredString(0, "Blue Flag");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			// Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 2:
			// Display third choice
			displayLCDCenteredString(0, "Blue Caps");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			// Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 3:
			// Display fourth choice
			displayLCDCenteredString(0, "Red Caps");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			// Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}
			break;
		default:
			count = 0;
			break;
		}
	}
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	switch (count) {

	case 0:// used to score the red bottom flag

		motor[servoLock] = 127;// drops the servo

		raise(12, 127, false);// raises the lift to hit the cap

		move(24, 100, false);// moves forward as the lift is raising

		spin(10, 100, false);// lines up with flag

		raiseWait();// waits for the lift to finish raising

		move(18, 80, false);// moves forward to hit the flag

		spin(15, 70, false);// spins to make sure the flag is scored

		spin(-15, 70,false);//spins to straight backward

		move(-25, 100, false);// backs up from the flag

		spin(80, 70, false);// spins to face towards the cap
		break;

	case 1: // used to score the bottom blue flag

		motor[servoLock] = 127;// drops the servo

		raise(12, 127, false);// raises the lift to 12 inches to hit the flag

		move(24, 100, false);// moves forward as the lift is raising

		raiseWait();// waits for the lift to finish raising

		move(15, 80, false);// moves forward to hit the flag

		spin(-30, 70, false);// spins to make sure the flag is scored

		spin(30, 70, false);//spins to straight backward

		move(-25, 100, false);// backs up from the flag

		spin(-80, 70, false);// spins to face towards the cap
		break;

	case 2: // used to score two blue low caps

		motor[servoLock] = 127;// drops the claw

		move(44, 127, false);// moves forward to the cap

		//raise(5, 127, false);
		// not used at the moment
		//raiseWait();

		//spin(-50, 80, false);// knocks the ball out from under the first cap

		//spin(50, 80, false);// spins back straight

		move(-5, 100, false);// moves back from the cap

		spin(110, 100, false);//spins left towards the other cap

		move(-7, 127, false);//moves towards the other cap

		motor[fliperMotor] = 70;
		motor[rightMotor] = 15;
		motor[leftMotor] = 15;
		wait1Msec(400);

		//I decided to use time as the requirement for the motor running because it will allow us to sync all movements while the act of
		//flipping the cone is happening

		motor[fliperMotor] = 0;
		motor[rightMotor] = 0;
		motor[leftMotor] = 0;

		move(5, 100, false);//moves back from the cap

		motor[fliperMotor] = -50;

		wait1Msec(20);

		motor[fliperMotor] = 0;
		//raise(-5, 100, false);
		//not used at the moment
		//raiseWait();

		//move(-5, 127, false);
		break;

	case 3:// used to score two red low caps

		motor[servoLock] = 127;// drops the claw

		move(44, 127, false);// moves forward to the cap

		//raise(5, 127, false);
		// not used at the moment
		//raiseWait();

		//spin(-50, 80, false);// knocks the ball out from under the first cap

		//spin(50, 80, false);// spins back straight

		move(-5, 100, false);// moves back from the cap

		spin(-130, 100, false);//spins left towards the other cap

		move(-7, 127, false);//moves towards the other cap

		motor[fliperMotor] = 70;
		motor[rightMotor] = 15;
		motor[leftMotor] = 15;
		wait1Msec(300);

		//I decided to use time as the requirement for the motor running because it will allow us to sync all movements while the act of
		//flipping the cone is happening

		motor[fliperMotor] = 0;
		motor[rightMotor] = 0;
		motor[leftMotor] = 0;

		move(5, 100, false);//moves back from the cap

		motor[fliperMotor] = -50;

		wait1Msec(20);

		motor[fliperMotor] = 0;
		//raise(-5, 100, false);
		//not used at the moment
		//raiseWait();

		//move(-5, 127, false);
		break;
	}
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	bool halfspeed = false;
	//PID fixup
	nMotorPIDSpeedCtrl[rightMotor] = RegIdle;
	nMotorPIDSpeedCtrl[leftMotor] = RegIdle;
	motor[servoLock] = 127;

	// User control code here, inside the loop

	while (true)
	{
		//Driving Motor Control
		if (vexRT[Btn8D] == 1)
		{
			halfspeed = true;
		}
		else if (vexRT[Btn8L] == 1)
		{
			halfspeed = false;
		}

		if (halfspeed == true)
		{
			motor[leftMotor] = vexRT[Ch3] / 4;
			motor[rightMotor] = vexRT[Ch2] / 4;
		}
		else
		{
			motor[leftMotor] = vexRT[Ch3];
			motor[rightMotor] = vexRT[Ch2];
		}
		//Lift Motor Control
		if (vexRT[Btn6U] == 1)
		{
			motor[liftMotor] = 127;
		}
		else if (vexRT[Btn6D] == 1)
		{
			motor[liftMotor] = -127;
		}
		else
		{
			motor[liftMotor] = 0;
		}

		// fliper control
		if (vexRT[Btn5U]==1)
		{
			motor[fliperMotor] = 70;
		}
		else if (vexRT[Btn5D] == 1)
		{
			motor[fliperMotor] = -40;
		}

		else
		{
			motor[fliperMotor] = 0;
		}



		sleep(10);
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		// Remove this function call once you have "real" code.
		UserControlCodePlaceholderForTesting();
	}
}
