#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl11, Flag,           sensorDigitalIn)
#pragma config(Sensor, dgtl12, Red,            sensorDigitalIn)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, PIDControl, encoderPort, I2C_1)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port6,           servoLock,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           spoolerMotor,  tmotorNone, openLoop)
#pragma config(Motor,  port9,           liftMotor,     tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

static const float ticksPerInch = 0.967 * (627.2 / (4.0 * PI));
// for moving forward or backwords
static const float ticksPerDeg = 1.0 * (ticksPerInch * 15.5 * PI) / 360.0;
// for turning the Robot
static const float ticksPerInchRaised = 3968.0/14.0; // * (627.2 * 0.75 * PI);
// for raising the lift
/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

//used to drive the robot forward
void move(float dist, int speed, bool hold)		//used to drive the robot forward
{
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);

	setMotorTarget(rightMotor, dist*ticksPerInch, speed, hold);
	setMotorTarget(leftMotor, dist*ticksPerInch, speed, hold);

	while (!getMotorTargetCompleted(rightMotor) && !getMotorTargetCompleted(leftMotor))
		wait1Msec(10);
}

//used to turn the robot
void spin(float deg, int speed, bool hold)	//used to turn the robot
{
	resetMotorEncoder(rightMotor);
	resetMotorEncoder(leftMotor);

	setMotorTarget(rightMotor, -deg * ticksPerDeg, speed, hold);
	setMotorTarget(leftMotor, deg * ticksPerDeg, speed, hold);

	while (!getMotorTargetCompleted(rightMotor) && !getMotorTargetCompleted(leftMotor))
		wait1Msec(10);
}

//used to raise the lift
void raise (float inches, int speed, bool hold)
{
	resetMotorEncoder(liftMotor);

	setMotorTarget(liftMotor, (long)(inches * ticksPerInchRaised), speed, hold);
}
void raiseWait (void)
{
	while (!getMotorTargetCompleted(liftMotor))
		wait1Msec(10);
}

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	if((SensorValue[Red] == 0) && (SensorValue[Flag] == 0))
	{
		motor[servoLock] = 10;

		raise(12, 127, false);

		move(24, 100, false);

		raiseWait();

		move(18, 80, false);

		spin(15, 70, false);

		spin(-15, 70,false);

		move(-25, 100, false);

		spin(80, 70, false);
	}
	else if((SensorValue[Red] == 1) && (SensorValue[Flag] == 0))
	{
		motor[servoLock] = 10;

		raise(12, 127, false);

		move(24, 100, false);

		raiseWait();

		move(15, 80, false);

		spin(-30, 70, false);

		spin(30, 70, false);

		move(-25, 100, false);

		spin(-80, 70, false);
	}

	else if((SensorValue[Red]) == 1 && (SensorValue[Flag] == 1))
	{
		motor[servoLock] = 10;

		move(40, 127, false);

		spin(15, 70, false);

		move(10, 80, false);

		raise(5, 127, false);

		raiseWait();

		move(-5, 70, false);

		raise(-5, 100, false);

		raiseWait();

		move(-5, 127, false);

	}
}
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	//PID fixup
	nMotorPIDSpeedCtrl[rightMotor] = RegIdle;
	nMotorPIDSpeedCtrl[leftMotor] = RegIdle;
	motor[servoLock] = 10;

	// User control code here, inside the loop

	while (true)
	{
		//Driving Motor Control
		motor[leftMotor] = vexRT[Ch3] / 2;
		motor[rightMotor] = vexRT[Ch2] / 2;

		//Lift Motor Control
		if (vexRT[Btn6U] == 1)
		{
			motor[liftMotor] = 127;
			motor[spoolerMotor] = -20;
		}
		else if (vexRT[Btn6D] == 1)
		{
			motor[liftMotor] = -127;
			motor[spoolerMotor] = 20;
		}
		else
		{
			motor[liftMotor] = 0;
		}

		// control spooler
		if (vexRT[Btn5D] == 1)
		{
			motor[spoolerMotor] = 20;
		}
		else if (vexRT[Btn5U] == 1)
		{
			motor[spoolerMotor] = -20;
		}
		else if ((vexRT[Btn6D] == 0) && (vexRT[Btn6U] == 0))
		{
			motor[spoolerMotor] = 0;
		}

		sleep(10);
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		// Remove this function call once you have "real" code.
		UserControlCodePlaceholderForTesting();
	}
}
